# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec for Whisper-Free on Windows.

Build with:
    pyinstaller --noconfirm --clean packaging/windows/Whisper-Free.spec

Produces dist/Whisper-Free/ — a **onedir** bundle (not onefile: a ~1.3 GB
onefile would extract to a temp dir on every launch, per ADR-0001 / issue #20).
Wrap it in the Inno Setup installer (packaging/windows/installer.iss, #21) via
scripts/build_windows.ps1.
"""
from __future__ import annotations

import sys
from pathlib import Path

from PyInstaller.utils.hooks import collect_dynamic_libs, collect_submodules

assert sys.platform == 'win32', \
    "This spec is for Windows only. Use packaging/macos or packaging/appimage elsewhere."

# Resolve repo root. SPECPATH is provided by PyInstaller; spec lives in
# packaging/windows/, so parents[1] is the repo root.
ROOT = Path(SPECPATH).resolve().parents[1]

# ---------------------------------------------------------------------------
# NVIDIA CUDA runtime (cuBLAS/cuDNN) so the GPU path works with no system
# CUDA install. These come from the nvidia-cublas-cu12 / nvidia-cudnn-cu12
# pip packages (requirements-windows.txt) and ship their DLLs under
# nvidia/<lib>/bin in site-packages. Collected only if installed, so a
# CPU-only dev build (no NVIDIA packages) still succeeds -- the resulting
# bundle just won't have GPU support.
# ---------------------------------------------------------------------------

cuda_binaries = []
for pkg in ('nvidia.cublas', 'nvidia.cudnn'):
    try:
        cuda_binaries += collect_dynamic_libs(pkg)
    except Exception as exc:  # pragma: no cover - build-time diagnostic only
        print(f"Warning: could not collect {pkg} DLLs ({exc}); "
              f"the bundle will be CPU-only.")

# ---------------------------------------------------------------------------
# Bundled ffmpeg.exe so MP3/M4A/WebM file transcription works with no system
# FFmpeg on PATH. Expected to be placed at packaging/windows/ffmpeg.exe before
# building (see scripts/build_windows.ps1 for the download step). Bundled at
# the root of the onedir output, next to Whisper-Free.exe, so
# app.platform.windows.init's PATH bootstrap (which prepends the exe's own
# directory) finds it.
# ---------------------------------------------------------------------------

ffmpeg_path = ROOT / 'packaging' / 'windows' / 'ffmpeg.exe'
ffmpeg_datas = [(str(ffmpeg_path), '.')] if ffmpeg_path.exists() else []
if not ffmpeg_datas:
    print(f"Warning: {ffmpeg_path} not found; the bundle will not include "
          f"ffmpeg.exe, so MP3/M4A/WebM file transcription will require a "
          f"system FFmpeg on PATH.")

# App icon (generated by scripts/build_windows.ps1 from assets/app-icon-512.png
# if missing/stale).
icon_path = ROOT / 'assets' / 'app-icon.ico'

asset_datas = [
    (str(ROOT / 'assets' / 'app-icon.png'), 'assets'),
    (str(ROOT / 'assets' / 'app-icon-512.png'), 'assets'),
    (str(ROOT / 'THIRD_PARTY_NOTICES.md'), 'licenses'),
    (str(ROOT / 'licenses' / 'README.md'), 'licenses'),
    (str(ROOT / 'licenses' / 'LGPL-3.0.txt'), 'licenses'),
    (str(ROOT / 'licenses' / 'GPL-3.0.txt'), 'licenses'),
]
tray_icon = ROOT / 'assets' / 'tray-icon.ico'
if tray_icon.exists():
    asset_datas.append((str(tray_icon), 'assets'))

a = Analysis(
    [str(ROOT / 'app' / 'main.py')],
    pathex=[str(ROOT)],
    binaries=cuda_binaries,
    datas=asset_datas + ffmpeg_datas,
    hiddenimports=[
        # pynput's win32 backend.
        'pynput.keyboard._win32',
        'pynput.mouse._win32',
        'pynput._util.win32',
        # faster-whisper / ctranslate2 + HF hub for model downloads.
        'huggingface_hub',
        *collect_submodules('faster_whisper'),
        *collect_submodules('ctranslate2'),
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    # Exclude the Linux/macOS-only backends to keep the bundle size down.
    excludes=[
        'torch',
        'torchaudio',
        'torchvision',
        'whisper',          # openai-whisper
        'mlx',
        'mlx_whisper',
        'noisereduce',
        'webrtcvad',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='Whisper-Free',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,           # UPX can trip AV heuristics on unsigned executables
    console=False,       # GUI app -- no console window
    disable_windowed_traceback=False,
    icon=str(icon_path) if icon_path.exists() else None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    name='Whisper-Free',
)
